project_id = "zkpsbrhadbblpsnhdlav"

[functions.manage-products]
verify_jwt = true

[functions.manage-categories]
verify_jwt = true

[functions.manage-tags]
verify_jwt = true

[functions.cmi-payment]
verify_jwt = false

[functions.manage-orders]
verify_jwt = true

[functions.manage-customers]
verify_jwt = true

[functions.manage-promo-codes]
verify_jwt = true

[functions.manage-recipes]
verify_jwt = true

[functions.manage-banners]
verify_jwt = true

[functions.manage-payments]
verify_jwt = true

[functions.bulk-update-product-images]
verify_jwt = true

[functions.create-customer-with-auth]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = false